
version: '3.1'
volumes:
  postgres_data: {}

services:
  app:
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rails db:migrate
        bundle exec rails s -p ${RAILS_PORT} -b ${RAILS_BIND}
    env_file:
      - '.env_production'
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
  web:
    env_file:
      - '.env_production'
    depends_on:
      - app
    ports:
      - 80:80
