
version: '3.1'
volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/prod.app.Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rails db:migrate
        bundle exec rails s -p ${RAILS_PORT} -b ${RAILS_BIND}
    env_file:
      - '.env_production'
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file:
      - '.env_production'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/web/web.Dockerfile
    env_file:
      - '.env_production'
    depends_on:
      - app
    ports:
      - 80:80
