version: '3.1'

services:
  luxfacta-polls:
    build:
      context: .
      dockerfile: ./docker/app/dev.app.Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rails db:drop
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails s -p ${RAILS_PORT} -b ${RAILS_BIND}
    env_file:
      - '.env'
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file:
      - '.env'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:Z
