
version: '3.1'
volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/prod.app.Dockerfile
      args:
        INSTALL_PATH: "/${COMPOSE_PROJECT_NAME}"
        RAILS_PORT: ${RAILS_PORT}
    volumes:
      - ./luxfacta-polls/${COMPOSE_PROJECT_NAME}
  web:
    build:
      context: .
      dockerfile: ./docker/web/web.Dockerfile
      args:
        INSTALL_PATH: "/${COMPOSE_PROJECT_NAME}"
        RAILS_PORT: ${RAILS_PORT}
