version: '3.1'

services:
  luxfacta-polls:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_PATH: "/${COMPOSE_PROJECT_NAME}"
        RAILS_PORT: ${RAILS_PORT}
    stdin_open: true
    tty: true
    environment:
      DEBUG: 'true'
    volumes:
      - "./:/${COMPOSE_PROJECT_NAME}"
