default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['LUXFACTA_POLLS_DATABASE_HOST'] %>
  port: <%= ENV['LUXFACTA_POLLS_DATABASE_PORT'] %>
  username: <%= ENV['LUXFACTA_POLLS_DATABASE_USERNAME'] %>
  password: <%= ENV['LUXFACTA_POLLS_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: luxfacta_polls_development

test:
  <<: *default
  database: luxfacta_polls_test

production:
  <<: *default
  database: luxfacta_polls_production
