default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: luxfacta_polls_development

test:
  <<: *default
  database: luxfacta_polls_test

production:
  <<: *default
  database: luxfacta_polls_production
  host: <%= ENV['LUXFACTA_POLLS_DATABASE_PRODUCTION_HOST'] %>
  port: <%= ENV['LUXFACTA_POLLS_DATABASE_PRODUCTION_PORT'] %>
  username: <%= ENV['LUXFACTA_POLLS_DATABASE_PRODUCTION_USERNAME'] %>
  password: <%= ENV['LUXFACTA_POLLS_DATABASE_PRODUCTION_PASSWORD'] %>
